/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_schaeuffelhut_android_openvpn_shared_util_JniUtil */

#ifndef _Included_de_schaeuffelhut_android_openvpn_shared_util_JniUtil
#define _Included_de_schaeuffelhut_android_openvpn_shared_util_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_schaeuffelhut_android_openvpn_shared_util_JniUtil
 * Method:    closeImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_schaeuffelhut_android_openvpn_shared_util_JniUtil_closeImpl
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_schaeuffelhut_android_openvpn_shared_util_JniUtil
 * Method:    asInt
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_de_schaeuffelhut_android_openvpn_shared_util_JniUtil_asInt
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
